#!/bin/bash

SCRIPT_DIR=$(dirname ${BASH_SOURCE:-$0})
. "$SCRIPT_DIR"/../funcs

# read sdcrc
if [ -r "$SCRIPT_DIR/sdcrc" ]; then
    . "$SCRIPT_DIR/sdcrc"
fi

CHECK=OK
if [ -z "$SDC_REPO" ]; then
    echo "[ERROR] SDC_REPO has not been set"
    CHECK=NOTOK
fi
if [ -z "$WORKSPACE" ]; then
    echo "[ERROR] WORKSPACE has not been set"
    CHECK=NOTOK
fi
if ! check-cmd curl; then
    echo "[ERROR] curl is not installed"
    CHECK=NOTOK
fi
if ! check-cmd docker; then
    echo "[ERROR] docker is not installed"
    CHECK=NOTOK
fi
if [ $CHECK != OK ]; then
    echo "[ERROR] Prerequisites not met. Aborting"
    exit 1
fi

# Clone SDC source tree
mkdir -p $(dirname $SDC_REPO) && cd $(dirname $SDC_REPO)
if [ -f "$(basename $SDC_REPO)/pom.xml" ]; then
    echo "[INFO] SDC local repo already exists. skip cloning"
else
    echo "[INFO] Cloning SDC repo into $SDC_REPO ..."
    git clone "https://gerrit.onap.org/r/sdc" $SDC_REPO
fi

# Prepare workspace
mkdir -p $WORKSPACE/data/scripts
mkdir -p $WORKSPACE/data/environments

# Copy docker scripts into the workspace
cp $SDC_REPO/sdc-os-chef/scripts/*.sh $WORKSPACE/data/scripts
cp $SDC_REPO/sdc-os-chef/environments/Template.json $WORKSPACE/data/environments/AUTO.json
# Obtain my IP and replace IPs in an env file
MY_IP=$(get-my-ip)
echo "[INFO] Your IP is $MY_IP"
case `uname -s` in
Linux)
    sed -i "s/yyy/$MY_IP/g" $WORKSPACE/data/environments/AUTO.json
    sed -i 's/xxx/AUTO/g' $WORKSPACE/data/environments/AUTO.json
    ;;
Darwin)
    sed -i '' "s/yyy/$MY_IP/g" $WORKSPACE/data/environments/AUTO.json
    sed -i '' 's/xxx/AUTO/g' $WORKSPACE/data/environments/AUTO.json
    ;;
esac

mkdir -p $WORKSPACE/opt/config/
echo AUTO > $WORKSPACE/opt/config/env_name.txt
echo nexus3.onap.org:10001 > $WORKSPACE/opt/config/nexus_docker_repo.txt
echo docker > $WORKSPACE/opt/config/nexus_username.txt
echo docker > $WORKSPACE/opt/config/nexus_password.txt

# Setup Maven settings.xml
mkdir -p $HOME/.m2
cd $HOME/.m2
if [ -f settings.xml ]; then
    echo "[INFO] ~/.m2/settings.xml already exists. skip configuring"
else
    echo "[INFO] Saving https://git.onap.org/oparent/plain/settings.xml as ~/.m2/settings.xml"
    curl -LO "https://git.onap.org/oparent/plain/settings.xml"
fi

echo "[INFO] SDC environment has been set up."
